project/FlightTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from booksystem import views

urlpatterns = [
    # url(r'^booksystem/admin/', admin.site.urls),
    url(r'^booksystem/admin/finance', views.admin_finance, name='admin_finance'),  # 财务管理
    url(r'^booksystem/', include('booksystem.urls')),
    url(r'', include('booksystem.urls')),
]

project/booksystem/urls.py
from django.conf.urls import url
from . import views

app_name = 'booksystem'  # 添加这个属性，方便jinja语法

urlpatterns = [
    # 注册与登录
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^login_user/$', views.login_user, name='login_user'),  # 登入
    url(r'^logout_user/$', views.logout_user, name='logout_user'),  # 登出

    # 主要页面
    url(r'^$', views.index, name='index'),  # 欢迎页面
    url(r'^result/$', views.result, name='result'),  # 搜索结果
    url(r'^user_info/$', views.user_info, name='user_info'),  # 用户信息
    url(r'^book/flight/(?P<flight_id>[0-9]+)/$', views.book_ticket, name='book_ticket'),  # 订票
    url(r'^refund/flight/(?P<flight_id>[0-9]+)/$', views.refund_ticket, name='refund_ticket'),  # 退票
    url(r'^admin/$', views.admin, name='user_admin'),
    url(r'^tourgroup/$',views.tourgroup,name='tourgroup'),
    url(r'^group_result/$',views.result_group,name='result_group'),
    url(r'^group_manage/$',views.group_manage,name='group_manage'),
    url(r'^group_book/flight/(?P<flight_id>[0-9]+)/$',views.group_book,name='group_book'),
    url(r'^group_refund/flight/(?P<flight_id>[0-9]+)/$',views.group_refund,name='group_refund'),
    url(r'^group_info/$',views.group_info,name='group_info'),
    url(r'^group_remove_member/(?P<member_id>[0-9]+)/$',views.group_remove_member,name='group_remove_member')
]

project/booksystem/models.py
# from django.contrib.auth.models import Permission, User
# import django.contrib.auth.models
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    # username = models.CharField(max_length=20, primary_key=True)
    # password = models.CharField(max_length=30)
    # email = models.EmailField()
    # phone = models.CharField(max_length=15)
    pid = models.IntegerField(default = 1)  # 权限 ID

    # def set_password(self, psw):
    #     self.password = psw
    #
    # def check_password(self, psw):
    #     if psw == self.password:
    #         return True
    #     else:
    #         return False





# Create your models here.
# 添加primary_key会覆盖掉默认的主键
class Flight(models.Model):
    user = models.ManyToManyField(User, default = 1)  # 有了这个字段之后，默认的后台添加失效，必须要自定义Form，除去这个字段
    name = models.CharField(max_length = 100)  # 班次  南方航空CZ3969
    leave_city = models.CharField(max_length = 100, null = True)  # 离开城市
    arrive_city = models.CharField(max_length = 100, null = True)  # 到达城市
    leave_airport = models.CharField(max_length = 100, null = True)  # 离开的机场
    arrive_airport = models.CharField(max_length = 100, null = True)  # 到达的机场
    leave_time = models.DateTimeField(null = True)  # DateTimeField包括了DateField信息，并且添加了时间
    arrive_time = models.DateTimeField(null = True)
    capacity = models.IntegerField(default = 0, null = True)  # 座位总数
    price = models.FloatField(default = 0, null = True)  # 价格
    book_sum = models.IntegerField(default = 0, null = True)  # 订票总人数
    income = models.FloatField(default = 0, null = True)  # 收入

    def __str__(self):
        return self.name

class Group(models.Model):
    id = models.AutoField(primary_key=True)
    name=models.CharField(max_length=64,null=False,unique=True)
    users = models.ManyToManyField(User, default=1)  # 一个旅行团拥有多个用户，一个用户可以加入多个旅行团
    flight=models.ManyToManyField(Flight,default=1)  # 一个旅行团能订多辆航班，一辆航班可以被多个旅行团预订

project/booksystem/forms.py
from django import forms
# from django.contrib.auth.models import User
from .models import Flight, User


class PassengerInfoForm(forms.Form):
    leave_city = forms.CharField(label='leave_city', max_length=100)
    arrive_city = forms.CharField(label='arrive_city', max_length=100)
    leave_date = forms.DateField(label='leave_date')


class MemberInfo(forms.Form):
    member_id = forms.IntegerField(label='member_id',max_value=10000)
    member_name = forms.CharField(label='member_name', max_length=100)


# 自定义Flight对象的输入信息
class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        exclude = ['user', 'book_sum', 'income']  # user信息不能从后台输入


# 用户需要输入的字段
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'pid']

project/booksystem/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from .forms import PassengerInfoForm, UserForm, FlightForm, MemberInfo
from .models import Flight, User, Group
from .classes import IncomeMetric, Order
# from django.contrib.auth.models import Permission, User
import datetime, pytz
from operator import attrgetter

ADMIN_ID = 1

global_passenger_lcity = None
global_passenger_acity = None
global_passenger_ldate = None
global_usable_flights_by_ltime = None
global_usable_flights_by_atime = None
global_usable_flights_by_price = None


# 管理员后台财务管理
# 统计航空公司每周、每月，每年营业收入情况。
def admin_finance(request):
    all_flights = Flight.objects.all()
    all_flights = sorted(all_flights, key=attrgetter('leave_time'))  # 将所有航班按照起飞时间排序

    # 将航班每天的输入打上不同的时间标签 [周，月，日]
    week_day_incomes = []
    month_day_incomes = []
    year_day_incomes = []

    # 用set存储所有的 周，月，年
    week_set = set()
    month_set = set()
    year_set = set()
    for flight in all_flights:
        if flight.income > 0:  # 只统计有收入的航班
            # 打上周标签
            this_week = flight.leave_time.strftime('%W')  # datetime获取周
            week_day_incomes.append((this_week, flight.income))  # 添加元组(week, income)
            week_set.add(this_week)
            # 打上月标签
            this_month = flight.leave_time.strftime('%m')  # datetime获取月
            month_day_incomes.append((this_month, flight.income))  # 添加元组(month, income)
            month_set.add(this_month)
            # 打上年标签
            this_year = flight.leave_time.strftime('%Y')  # datetime获取年
            year_day_incomes.append((this_year, flight.income))  # 添加元组(year, income)
            year_set.add(this_year)

    # 存储每周收入
    # 将每周的收入用 IncomeMetric 类型存储在 week_incomes List中
    week_incomes = []
    for week in week_set:
        income = sum(x[1] for x in week_day_incomes if x[0] == week)  # 同周次的income求和
        flight_sum = sum(1 for x in week_day_incomes if x[0] == week)  # 同周次的航班总数目
        week_income = IncomeMetric(week, flight_sum, income)  # 将数据存储到IncomeMetric类中，方便jinja语法
        week_incomes.append(week_income)
    week_incomes = sorted(week_incomes, key=attrgetter('metric'))  # 将List类型的 week_incomes 按周次升序排列

    # 存储每月收入
    # 将每月的收入用 IncomeMetric 类型存储在 month_incomes List中
    month_incomes = []
    for month in month_set:
        income = sum(x[1] for x in month_day_incomes if x[0] == month)
        flight_sum = sum(1 for x in month_day_incomes if x[0] == month)
        month_income = IncomeMetric(month, flight_sum, income)
        month_incomes.append(month_income)
    month_incomes = sorted(month_incomes, key=attrgetter('metric'))  # 将List类型的 month_incomes 按月份升序排列

    # 存储每年收入
    # 将每年的收入用 IncomeMetric 类型存储在 year_incomes List中
    year_incomes = []
    for year in year_set:
        income = sum(x[1] for x in year_day_incomes if x[0] == year)
        flight_sum = sum(1 for x in year_day_incomes if x[0] == year)
        year_income = IncomeMetric(year, flight_sum, income)
        year_incomes.append(year_income)
    year_incomes = sorted(year_incomes, key=attrgetter('metric'))  # 将List类型的 year_incomes 按年份升序排列

    # 存储order信息
    passengers = User.objects.exclude(pk=1)  # 去掉管理员
    order_set = set()
    for p in passengers:
        flights = Flight.objects.filter(user=p)
        for f in flights:
            route = f.leave_city + ' → ' + f.arrive_city
            order = Order(p.username, f.name, route, f.leave_time, f.price)
            order_set.add(order)

    # 信息传给前端
    context = {
        'week_incomes': week_incomes,
        'month_incomes': month_incomes,
        'year_incomes': year_incomes,
        'order_set': order_set
    }
    return context


# 管理员添加航班
def admin(request):
    if request.method == 'POST':
        form = FlightForm(request.POST)  # 绑定数据至表单
        if form.is_valid():
            flight = form.save(commit=False)
            flight.save()
            return render(request, 'booksystem/admin.html')
        else:
            print("无效！")
            return render(request, 'booksystem/admin.html')

    else:
        return render(request, 'booksystem/admin.html')


# 显示用户订单信息
# 航班信息，退票管理
def user_info(request):
    if request.user.is_authenticated:
        # 如果用户是管理员，render公司航班收入统计信息页面 admin_finance
        if request.user.id == ADMIN_ID:
            context = admin_finance(request)  # 获取要传入前端的数据
            # return render(request, 'booksystem/admin_finance.html', context)
        # 如果用户是普通用户，render用户的机票信息 user_info
        else:
            booked_flights = Flight.objects.filter(user=request.user)  # 从 booksystem_flight_user 表过滤出该用户订的航班
            context = {
                'booked_flights': booked_flights,
                'username': request.user.username,  # 导航栏信息更新
            }
            return render(request, 'booksystem/user_info.html', context)
    return render(request, 'booksystem/login.html')  # 用户如果没登录，render登录页面


# 主页
# 欢迎页面性质的订票页面
def index(request):
    return render(request, 'booksystem/result.html')


# 免除csrf
@csrf_exempt
def book_ticket(request, flight_id):
    if not request.user.is_authenticated:  # 如果没登录就render登录页面
        return render(request, 'booksystem/login.html')
    else:
        flight = Flight.objects.get(pk=flight_id)
        # 查看乘客已经订购的flights
        booked_flights = Flight.objects.filter(user=request.user)  # 返回 QuerySet

        if flight in booked_flights:
            return render(request, 'booksystem/book_conflict.html')

        # book_flight.html 点确认之后，request为 POST 方法，虽然没有传递什么值，但是传递了 POST 信号
        # 确认订票，flight数据库改变

        # 验证一下，同样的机票只能订一次
        if request.method == 'POST':
            if flight.capacity > 0:
                flight.book_sum += 1
                flight.capacity -= 1
                flight.income += flight.price
                flight.user.add(request.user)
                flight.save()  # 一定要记着save
        # 传递更改之后的票务信息
        context = {
            'flight': flight,
            'username': request.user.username
        }
        return render(request, 'booksystem/book_flight.html', context)


# 退票
def refund_ticket(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    flight.book_sum -= 1
    flight.capacity += 1
    flight.income -= flight.price
    flight.user.remove(request.user)
    flight.save()
    return HttpResponseRedirect('/booksystem/user_info')


def group_refund(request, flight_id):
    group_obj = Group.objects.get(name=request.user.username)
    group_user = group_obj.users.all()
    flight = Flight.objects.get(pk=flight_id)
    group_obj.flight.remove(flight)
    for user in group_user:
        booked_flights_user = Flight.objects.filter(user=user)
        if flight in booked_flights_user:
            flight.user.remove(user)
            flight.book_sum -= 1
            flight.capacity += 1
            flight.income -= flight.price
    group_obj.save()
    flight.save()
    return HttpResponseRedirect('/booksystem/group_info')


def group_remove_member(request, member_id):
    group_obj = Group.objects.get(name=request.user.username)
    user = User.objects.get(pk=member_id)
    group_obj.users.remove(user)
    group_obj.save()
    return HttpResponseRedirect('/booksystem/group_manage')


# 退出登录
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'booksystem/login.html', context)


# 登录
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        user = authenticate(username=username, password=password)
        if user is not None:  # 登录成功
            if user.is_active:  # 加载订票页面
                login(request, user)
                context = {
                    'username': request.user.username
                }
                if user.id == ADMIN_ID:
                    # context = admin_finance(request)  # 获取要传入前端的数据
                    return render(request, 'booksystem/admin.html')
                else:
                    if user.pid == 1:
                        return render(request, 'booksystem/result.html', context)
                    else:
                        print("旅行团")
                        context = {
                            'username': "旅行团"
                        }
                        # print("旅行团")
                        return render(request, 'booksystem/tourgroup.html')
            else:
                return render(request, 'booksystem/login.html', {'error_message': 'Your account has been disabled'})
        else:  # 登录失败
            return render(request, 'booksystem/login.html', {'error_message': 'Invalid login'})
    return render(request, 'booksystem/login.html')


# 注册
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                context = {
                    'username': request.user.username
                }
                if user.pid == 1:
                    return render(request, 'booksystem/result.html', context)  # 注册成功直接render result页面
                else:
                    # 创建一个新的group
                    newgroup = Group(name=request.user.username)
                    newgroup.save()
                    context = {
                        'username': "旅行团"
                    }
                    return render(request, 'booksystem/result.html', context)
    context = {
        "form": form,
    }

project/booksystem/templates/booksystem/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>机票管理系统</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {#    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">#}
    {% block style %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body style="background-color: #f1f1f1">
<nav class="nav navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'booksystem:index' %}">CSU Airlines</a>
        </div>
        <!-- Items -->
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'booksystem:result' %}">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; 购票
                </a>
            </li>
            <li>
                <a href="{% url 'booksystem:user_info' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 个人中心
                </a>
            </li>
            <li>
                {% block login_display %} <!--在用户登录之后改变这一块的显示内容-->
                    <a href="{% url 'booksystem:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; 登录
                    </a>
                {% endblock %}
            </li>
            <li>
                <a href="{% url 'booksystem:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; 退出
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

project/booksystem/templates/booksystem/book_conflict.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} 先生/女士</a> <!--用#就不会跳转了-->
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="alert" style="background-color: white;overflow: hidden"> <!--超出部分也是白色底-->
            <h1>尊敬的旅客</h1>
            <div id="info_body" style="margin-left: 50px;margin-right: 50px">
                <p>
                    您已经订购过该航班，请选择其他航班，祝您旅途愉快！
                </p>
            </div>

            <div id="book_btns" align="right">
                <!--div内容右对齐-->
                <a href="" class="btn btn-danger" style="width: 80px" onclick="history.back();">返回</a>
            </div>
        </div>
    </div>
{% endblock %}

project/booksystem/templates/booksystem/book_flight.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} 先生/女士</a> <!--用#就不会跳转了-->
{% endblock %}

{% block js %}
    <script>

        function confirm_info() {
            var remain_seats = document.getElementById('remain_seats').innerHTML;
            document.getElementById('book_btns').style.display = "none";
            if (remain_seats > 0) {
                document.getElementById('book_success').style.display = "block";
            } else {
                document.getElementById('book_failure').style.display = "block";
            }
        }

        // ajax异步刷新页面
        function PostData() {
            $.ajax({
                type: "POST",
                url: "",
                data: ""
            });
            return false; // 必须这一句，不然还会刷新页面
        }

    </script>
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="alert" style="background-color: white;overflow: hidden"> <!--超出部分也是白色底-->
            <h1>尊敬的旅客</h1>
            <div id="info_body" style="margin-left: 50px;margin-right: 50px">
                <p>
                    您选择了 <strong style="font-size: large"> {{ flight.name }} </strong> 次航班，
                    该航班还有余票
                    <strong id="remain_seats"
                            style="font-size: xx-large;color: #ff6600;font-style: italic">{{ flight.capacity }}</strong>
                    张。
                </p>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th style="text-align: center">航班</th>
                        <th style="text-align: center">起飞机场</th>
                        <th style="text-align: center">到达机场</th>
                        <th style="text-align: center">起飞时间</th>
                        <th style="text-align: center">到达时间</th>
                        <th style="text-align: center">价格</th>
                    </tr>
                    </thead>
                    <tbody style="text-align: center">
                    <tr>
                        <td>{{ flight.name }}</td>
                        <td>{{ flight.leave_city }}{{ flight.leave_airport }}</td>
                        <td>{{ flight.arrive_city }}{{ flight.arrive_airport }}</td>
                        <td>{{ flight.leave_time }}</td>
                        <td>{{ flight.arrive_time }}</td>
                        <td>￥{{ flight.price }}</td>
                    </tr>
                    </tbody>
                </table>

                <div id="book_success" style="display: none">
                    <p style="color: green;font-size: large;font-weight: bold">
                        您已成功订购了此次航班，请保管好航班信息，祝您旅途愉快！
                    </p>
                </div>

                <div id="book_failure" style="display: none">
                    <p style="color: red;font-size: large;font-weight: bold">
                        该航班已无余票，请选择其他航班，祝您旅途愉快！
                    </p>
                </div>

                <div id="book_btns" align="right">
                    <!--div内容右对齐-->
                    <form onsubmit="return PostData()" method="post" style="display: inline">
                        <input class="btn btn-primary" style="width: 80px" value="确认" type="submit"
                               onclick="confirm_info()">
                    </form>
                    <a href="{% url 'booksystem:result' %}" class="btn btn-danger" style="width: 80px" onclick="">返回</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/booksystem/templates/booksystem/group_book_conflict.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} 先生/女士</a> <!--用#就不会跳转了-->
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="alert" style="background-color: white;overflow: hidden"> <!--超出部分也是白色底-->
            <h1>尊敬的旅客</h1>
            <div id="info_body" style="margin-left: 50px;margin-right: 50px">
                <p>
                    您已经订购过该航班，请选择其他航班，祝您旅途愉快！
                </p>
            </div>

            <div id="book_btns" align="right">
                <!--div内容右对齐-->
<!--                <a href="" class="btn btn-danger" style="width: 80px" onclick="history.back();">返回</a>-->
                <a href="{% url 'booksystem:tourgroup' %}" class="btn btn-danger" style="width: 80px" onclick="">返回</a>
            </div>
        </div>
    </div>
{% endblock %}

project/booksystem/templates/booksystem/group_manage.html
{% extends 'booksystem/base.html' %}

{% block style %}
    <style>
        .main {
            margin-top: 20px;
            margin-left: 50px;
            margin-right: 50px;
        }
    </style>
{% endblock %}

{% block js %}
    <script>
        function remove(member_id) {
            var choice = confirm("确定要移除该成员吗?");
            if (choice == true) {
                window.location = "/group_remove_member/" + member_id;
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="search_form">
    <div class="col-sm-12" style="margin-top: 20px">
        <form action="{% url 'booksystem:group_manage' %}" method="post">
            {% csrf_token %}
            <div class="col-sm-3"> {# 在父div中要指定width:100%才会一样宽 #}
                <span class="ico_search_type ico_search_acity"></span><br>
                <input class="my_input" type="number" id="member_id" name="member_id" placeholder="member_id"
                       value="{{ member_id }}">
            </div>
            <div class="col-sm-3">
                <span class="ico_search_type ico_search_acity"></span><br>
                <input class="my_input" type="text" id="member_name" name="member_name" placeholder="member_name"
                       value="{{ member_name }}">
            </div>
            <div class="col-sm-3">
                <div style="position: absolute;margin-top: 10px;margin-left: 35%">
                    <input class="btn btn btn-info" name="add" type="submit" value="加入">
                    <span class="text-danger small">{{ error }}</span>
                </div>

            </div>
        </form>

    </div>
</div>



<div class="main">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th style="text-align: center">成员id</th>
            <th style="text-align: center">成员名称</th>
        </tr>
        </thead>
        <tbody style="text-align: center">
        {% for member in members %}
            <tr>
                <td>{{ member.id }}</td>
                <td>{{ member.username }}
                <button class="btn btn-sm btn-danger" onclick="remove({{ member.id }})">移除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--<div>-->
<!--    {% for member in members %}-->
<!--        <div class="one_line">-->
<!--            <div class="col-sm-12">-->
<!--                <div class="col-sm-3">-->
<!--                    <p class="flight_name">{{ member.id }}</p> {# 单行居中 #}-->
<!--                </div>-->
<!--                <div class="col-sm-3">-->
<!--                    <p class="flight_name">{{ member.username }}</p> {# 单行居中 #}-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    {% endfor %}-->
<!--</div>-->



<a href="{% url 'booksystem:tourgroup' %}" class="btn btn-danger" style="width: 80px" onclick="">返回</a>
{% endblock %}

project/booksystem/templates/booksystem/login.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>登录账号</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="{% url 'booksystem:login_user' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_username">
                                    用户名:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_username" maxlength="10" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_password">
                                    密码:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_password" maxlength="10" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Don't have an account? <a href="{% url 'booksystem:register' %}">Click here</a> to register.
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

project/booksystem/templates/booksystem/register.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>注册账号</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
<!--                            {% include 'booksystem/form_template.html' %}-->
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ form.errors }}</span>
                                </div>
                                <label class="control-label col-sm-6" for="id_username">Username:</label>
                                <div class="col-sm-6">
                                    <input type="text" name="username" maxlength="150" required="" id="id_username">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ form.errors }}</span>
                                </div>
                                <label class="control-label col-sm-6" for="id_email">Email address:</label>
                                <div class="col-sm-6">
                                    <input type="email" name="email" maxlength="254" id="id_email">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ form.errors }}</span>
                                </div>
                                <label class="control-label col-sm-6" for="id_password">Password:</label>
                                <div class="col-sm-6">
                                    <input type="password" name="password" maxlength="254" id="id_password">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ form.errors }}</span>
                                </div>
                                <label class="control-label col-sm-6" for="id_pid">Pid:</label>
                                <div class="col-sm-6">
                                    <select name="pid" id="id_pid">
                                    <option value="1">旅客</option>
                                    <option value="2">旅行团</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Already have an account? <a href="{% url 'booksystem:login_user' %}">Click here</a> to log in.
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

project/booksystem/templates/booksystem/tourgroup.html
{% extends 'booksystem/base.html' %}

{% block style %}
<style xmlns="http://www.w3.org/1999/html">
</style>
{% endblock %}


{% block content %}
        <div class="main">
            <div class="search_form">
<!--                <div class="col-sm-12" style="margin-top: 20px">-->
                <a href="{% url 'booksystem:group_manage' %}" class="btn btn-danger" style="width: 80px" onclick="">旅行团信息管理</a>
                <a href="{% url 'booksystem:result_group' %}" class="btn btn-danger" style="width: 80px" onclick="">旅行团订购机票</a>
                <a href="{% url 'booksystem:group_info' %}" class="btn btn-danger" style="width: 80px" onclick="">旅行团机票查询</a>

<!--                </div>-->
            </div>
        </div>
{% endblock %}